[phases.setup]
nixPkgs = ["python313", "pip"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn scripts.backend_rag:app --host 0.0.0.0 --port $PORT"